import 'package:flutter/material.dart';
import 'package:flutter_chat_ui/flutter_chat_ui.dart';

@immutable
class CustomChatTheme extends ChatTheme {
  const CustomChatTheme({
    required Color background,
    required Color onBackground,
    required Color primary,
    required Color onPrimary,
    required Color secondary,
    required Color onSecondary,
  }) : super(
          attachmentButtonIcon: null,
          attachmentButtonMargin: null,
          backgroundColor: background,
          dateDividerMargin: const EdgeInsets.only(bottom: 32, top: 16),
          dateDividerTextStyle: const TextStyle(
            color: Colors.grey,
            fontSize: 12,
            fontWeight: FontWeight.w800,
            height: 1.333,
          ),
          deliveredIcon: null,
          documentIcon: null,
          emptyChatPlaceholderTextStyle: const TextStyle(
            color: Colors.grey,
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 1.5,
          ),
          errorColor: Colors.red,
          errorIcon: null,
          inputBackgroundColor: Colors.grey,
          inputSurfaceTintColor: Colors.grey,
          inputElevation: 0,
          inputBorderRadius: const BorderRadius.vertical(
            top: Radius.circular(20),
          ),
          inputContainerDecoration: null,
          inputMargin: EdgeInsets.zero,
          inputPadding: const EdgeInsets.fromLTRB(24, 20, 24, 20),
          inputTextColor: Colors.black,
          inputTextCursorColor: null,
          inputTextDecoration: const InputDecoration(
            border: InputBorder.none,
            contentPadding: EdgeInsets.zero,
            isCollapsed: true,
          ),
          inputTextStyle: const TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 1.5,
          ),
          messageBorderRadius: 20,
          messageInsetsHorizontal: 20,
          messageInsetsVertical: 16,
          messageMaxWidth: 440,
          primaryColor: Colors.blue,
          receivedEmojiMessageTextStyle: const TextStyle(fontSize: 40),
          receivedMessageBodyTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 1.5,
          ),
          receivedMessageCaptionTextStyle: const TextStyle(
            color: Colors.grey,
            fontSize: 12,
            fontWeight: FontWeight.w500,
            height: 1.333,
          ),
          receivedMessageDocumentIconColor: Colors.blue,
          receivedMessageLinkDescriptionTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 14,
            fontWeight: FontWeight.w400,
            height: 1.428,
          ),
          receivedMessageLinkTitleTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w800,
            height: 1.375,
          ),
          secondaryColor: Colors.green,
          seenIcon: null,
          sendButtonIcon: null,
          sendButtonMargin: null,
          sendingIcon: null,
          sentEmojiMessageTextStyle: const TextStyle(fontSize: 40),
          sentMessageBodyTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 1.5,
          ),
          sentMessageCaptionTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 12,
            fontWeight: FontWeight.w500,
            height: 1.333,
          ),
          sentMessageDocumentIconColor: Colors.black,
          sentMessageLinkDescriptionTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 14,
            fontWeight: FontWeight.w400,
            height: 1.428,
          ),
          sentMessageLinkTitleTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w800,
            height: 1.375,
          ),
          statusIconPadding: const EdgeInsets.symmetric(horizontal: 4),
          systemMessageTheme: const SystemMessageTheme(
            margin: EdgeInsets.only(bottom: 24, top: 8, left: 8, right: 8),
            textStyle: TextStyle(
              color: Colors.grey,
              fontSize: 12,
              fontWeight: FontWeight.w800,
              height: 1.333,
            ),
          ),
          typingIndicatorTheme: const TypingIndicatorTheme(
            animatedCirclesColor: Colors.grey,
            animatedCircleSize: 5.0,
            bubbleBorder: BorderRadius.all(Radius.circular(27.0)),
            bubbleColor: Colors.black,
            countAvatarColor: Colors.blue,
            countTextColor: Colors.green,
            multipleUserTextStyle: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w500,
              color: Colors.grey,
            ),
          ),
          unreadHeaderTheme: const UnreadHeaderTheme(
            color: Colors.green,
            textStyle: TextStyle(
              color: Colors.grey,
              fontSize: 12,
              fontWeight: FontWeight.w500,
              height: 1.333,
            ),
          ),
          userAvatarImageBackgroundColor: Colors.transparent,
          userAvatarNameColors: const [],
          userAvatarTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 12,
            fontWeight: FontWeight.w800,
            height: 1.333,
          ),
          userNameTextStyle: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w800,
            height: 1.333,
          ),
          highlightMessageColor: null,
        );
}
