name: 'Issue Reference'
on:
  pull_request:
    types: [opened, edited]
  push:
    branches: ["main"]

jobs:
  issue-reference:
    permissions:
      contents: write
      pull-requests: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/add-an-issue-reference-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-prefix: "DW-"